collections:
  /:
    permalink: /music/{slug}/
    template: index
    filter: tag:[newsletter,music]
  /newsletter/:
    permalink: /newsletter/{slug}/
    template: index
    filter: tag:newsletter

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
