collections:
  /:
    permalink: /music/{slug}/
    template: index
    filter: tag:[newsletter,music]
  /newsletter/:
    permalink: /newsletter/{slug}/
    template: index
    filter: tag:newsletter
  /album-new/:
    permalink: /album-new/{slug}/
    template: index
    filter: tag:album

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
